services:
  postgres:
    image: postgres:latest
    container_name: altametrics_postgres
    environment:
      POSTGRES_DB: altametrics
      POSTGRES_USER: altametrics
      POSTGRES_PASSWORD: altametrics
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U altametrics']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
